---
- name: FlexBook GDS Playbook - proxies
  become: true
  hosts: proxies
  remote_user: admin
  tasks:

  - name: Install NGINX
    pkgng:
      name: nginx
      state: present
  - name: Enable NGINX
    community.general.sysrc:
      name: nginx_enable
      value: "YES"
  - name: copying NGINX conf file
    copy:
      src: ./nginx/nginx.conf
      dest: /usr/local/etc/nginx/nginx.conf
      owner: root
      group: wheel
      mode: 0644
  - name: copying NGINX index.html file
    copy:
      src: ./nginx/index.html
      dest: /usr/local/www/nginx/index.html
      owner: root
      group: wheel
      mode: 0644
  - name: Restart NGINX
    service:
      name: nginx
      state: restarted
  - name: Install BIND
    pkgng:
      name: bind916
      state: present
  - name: Enable NAMED
    community.general.sysrc:
      name: named_enable
      value: "YES"
  - name: copying NAMED conf file
    copy:
      src: ./named/named.conf
      dest: /usr/local/etc/namedb/named.conf
      owner: root
      group: wheel
      mode: 0644
  - name: copying NAMED master db file - flxb.local.db
    copy:
      src: ./named/flxb.local.db
      dest: /usr/local/etc/namedb/master/flxb.local.db
      owner: root
      group: wheel
      mode: 0644
  - name: Restart BIND (NAMED)
    service:
      name: named
      state: restarted
  - name: Finished message
    debug:
      msg: Job done!
